src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\DBAL\Types\Types;


#[ORM\Entity(repositoryClass: PostRepository::class)]
class Post
{

    public const STATUS_PUBLIC = 'public';
    public const STATUS_PRIVATE = 'private';
    
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column (length: 255, type: 'string')]
    private string $status;

    #[ORM\Column(type: Types::TEXT)] 
    #[Assert\Regex(
        pattern: '/^[a-zA-Z0-9!@#$%^&*(),.?:{}|]*$/',
        message: 'Le champ peut contenir des lettres majuscules, minuscules, chiffres et certains symboles.'
    )] 
    #[Assert\NotBlank(message: "ce champs ne peut etre vide")]
    #[Assert\Length( min : 5, minMessage: 'Veuillez détailler votre post')]
    private ?string $content = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column]
    private ?int $rating = null;

    #[ORM\Column]
    private ?int $nbresponse = null;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    #[ORM\ManyToOne(inversedBy: 'posts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $author = null;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: Vote::class)]
    private Collection $votes;

    #[ORM\Column( nullable:true)]
    private ?string $picture = null;

    #[ORM\ManyToOne]
    private ?User $receiver = null;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
        $this->comments = new ArrayCollection();
        $this->votes = new ArrayCollection();
        $this->status = self::STATUS_PUBLIC;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function setStatus(string $status):self
    {
        $this->status =$status;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getRating(): ?int
    {
        return $this->rating;
    }

    public function setRating(int $rating): static
    {
        $this->rating = $rating;

        return $this;
    }

    public function getNbresonse(): ?int
    {
        return $this->nbresponse;
    }

    public function setNbresonse(int $nbresponse): static
    {
        $this->nbresponse = $nbresponse;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): static
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection<int, Vote>
     */
    public function getVotes(): Collection
    {
        return $this->votes;
    }

    public function addVote(Vote $vote): static
    {
        if (!$this->votes->contains($vote)) {
            $this->votes->add($vote);
            $vote->setPost($this);
        }

        return $this;
    }

    public function removeVote(Vote $vote): static
    {
        if ($this->votes->removeElement($vote)) {
            // set the owning side to null (unless already changed)
            if ($vote->getPost() === $this) {
                $vote->setPost(null);
            }
        }

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): static
    {
        $this->picture = $picture;

        return $this;
    }

    public function getReceiver(): ?User
    {
        return $this->receiver;
    }

    public function setReceiver(?User $receiver): static
    {
        $this->receiver = $receiver;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\Post;
use App\Entity\Comment;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: 'email', message: "Cet email est déjà utilisé.")]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\NotBlank(message: "Veuillez renseigner une adresse mail.")]
    #[Assert\Email(message: "Veuillez renseigner une adresse mail valide.")]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[Assert\Regex(
        pattern: '/^[a-zA-Z0-9!@#$%^&*(),.?:{}|]*$/',
        message: 'Le champ peut contenir des lettres majuscules, minuscules, chiffres et certains symboles.'
    )] 
    #[Assert\NotBlank(message: "Veuillez renseigner un mot de passe.")]
    #[Assert\Length(min: 5, minMessage:" Le mot de passe doit faire plus de 5 caracteres.")]
    private ?string $password = null;

   
    #[Assert\Length(min: 5, minMessage:" Le mot de passe doit faire plus de 5 caracteres.")]
    private ?string $newPassword = null;


    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Veuillez renseigner votr prénom.")]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Veuillez renseigner votr nom.")]
    private ?string $lastname = null;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Post::class, orphanRemoval: true)]
    private Collection $posts;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    #[ORM\Column( nullable:true)]
    private ?string $picture = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Vote::class, orphanRemoval: true)]
    private Collection $votes;

    #[ORM\OneToMany(mappedBy: 'requester', targetEntity: Friendship::class)]
    private Collection $friendships;

    #[ORM\OneToMany(mappedBy: 'receiver', targetEntity: Friendship::class)]
    private Collection $receiverFreindShips;

    public function __construct()
    {
        $this->roles = ['ROLE_USER'];
        $this->createdAt = new \DateTimeImmutable();
        $this->posts = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->votes = new ArrayCollection();
        $this->friendships = new ArrayCollection();
        $this->receiverFreindShips = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function getnewPassword(): ?string
    {
        return $this->newPassword;
    }

    public function setnewPassword(string $newPassword): static
    {
        $this->newPassword = $newPassword;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFullname() : string {
        return $this->firstname . ' ' .$this->lastname;
    }

    /**
     * @return Collection<int, Post>
     */
    public function getPost(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): static
    {
        if (!$this->posts->contains($post)) {
            $this->posts->add($post);
            $post->setAuthor($this);
        }

        return $this;
    }

    public function removePost(Post $post): static
    {
        if ($this->posts->removeElement($post)) {
            // set the owning side to null (unless already changed)
            if ($post->getAuthor() === $this) {
                $post->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): static
    {
        $this->picture = $picture;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection<int, Vote>
     */
    public function getVotes(): Collection
    {
        return $this->votes;
    }

    public function addVote(Vote $vote): static
    {
        if (!$this->votes->contains($vote)) {
            $this->votes->add($vote);
            $vote->setAuthor($this);
        }

        return $this;
    }

    public function removeVote(Vote $vote): static
    {
        if ($this->votes->removeElement($vote)) {
            // set the owning side to null (unless already changed)
            if ($vote->getAuthor() === $this) {
                $vote->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Friendship>
     */
    public function getFriendships(): Collection
    {
        return $this->friendships;
    }

    public function addFriendship(Friendship $friendship): static
    {
        if (!$this->friendships->contains($friendship)) {
            $this->friendships->add($friendship);
            $friendship->setRequester($this);
        }

        return $this;
    }

    public function removeFriendship(Friendship $friendship): static
    {
        if ($this->friendships->removeElement($friendship)) {
            // set the owning side to null (unless already changed)
            if ($friendship->getRequester() === $this) {
                $friendship->setRequester(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Friendship>
     */
    public function getReceiverFreindShips(): Collection
    {
        return $this->receiverFreindShips;
    }

    public function addReceiverFreindShip(Friendship $receiverFreindShip): static
    {
        if (!$this->receiverFreindShips->contains($receiverFreindShip)) {
            $this->receiverFreindShips->add($receiverFreindShip);
            $receiverFreindShip->setReceiver($this);
        }

        return $this;
    }

    public function removeReceiverFreindShip(Friendship $receiverFreindShip): static
    {
        if ($this->receiverFreindShips->removeElement($receiverFreindShip)) {
            // set the owning side to null (unless already changed)
            if ($receiverFreindShip->getReceiver() === $this) {
                $receiverFreindShip->setReceiver(null);
            }
        }

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\Image;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;

       class UserType extends AbstractType 
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $User = $builder->getData();
        $builder
        
        ->add('lastname',TextType::class,[
            'label' => 'Nom :'
            ])
            ->add('firstname',TextType::class,[
                'label' => 'Prénom :'
            ])
            ->add('email',EmailType::class,[
                'label' => 'Email :'
            ])
            
            ->add('picture', FileType::class,[
                'label' => 'Image de Profile :',
                'required' => $options['new_user'],
                'mapped' => false,
                'constraints' => [
                    new Image([
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                            'image/gif',
                        ],
                        'mimeTypesMessage' => "Veuillez télécharger une image valide",
                        "maxSize" => '2M',
                        'maxSizeMessage' => "Votre image fait {{size}} {{suffix}}, La limite est de {{ limit }} {{suffix}}"
                        ]),
                    ]
                ])
            ->add('password',  PasswordType::class,[
                'label' => 'Mot de Passe :',
               
            ]);
            
                // ->add('roles')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
            'new_user' => true
        ]);
    }
}

templates/user/changePassword.html.twig
{% extends 'base.html.twig' %}
{% block title %}Social World{% endblock %}
{% block body %} 
{% include "partials/_navBar.html.twig" %}
<div class="row">
{% include "partials/_notification.html.twig" %}
<div class="content-boby">
  <div class="profil-user">
    <header>
      <div class="user-info">
        <a href="{{ path('current_user') }}">
          <img src="{{ asset(app.user.picture) }} " alt="profil-picture" />
        </a>
        <h2>Bonjour {{ app.user.firstname }}</h2>
      </div>
      <div class="user-title">
        <h1>Modifiez Votre Mot de Passe</h1>
      </div>
      <div class="userform-password">
        {{ form_start(form) }}
        {{ form_rest(form) }}
        <button class="btn btn-primary">Modifier</button>
        {{ form_end(form) }}
      </div>
    </header>
  </div>
</div>
{% include "partials/_friendslist.html.twig" %}
</div>
{% endblock %}

templates/user/changeProfil.html.twig
{% extends 'base.html.twig' %}
{% block title %}Social World{% endblock %}
{%block body %}
 {% include "partials/_navBar.html.twig" %}
<div class="row">
  {% include "partials/_notification.html.twig" %}
  <div class="content-boby">
    <div class="profil-user">
      <header>
        <div class="user-info">
          <a href="{{ path('current_user') }}">
            <img src="{{ asset(app.user.picture) }} " alt="profil-picture" />
          </a>
          <h2>Bonjour {{ app.user.firstname }}</h2>
        </div>
        <div class="user-title">
          <h1>Modifiez Vos infos de Profil</h1>
        </div>
        <div class="userform">
          {{ form_start(form) }}
          {{ form_row(form.picture, { 'attr': {'style': 'display: none;'} }) }}
          <i id="upload-icon" class="fa-regular fa-image fa-2xl" style="cursor: pointer;"></i>
          {{ form_rest(form) }}
          
            <button class="btn btn-primary">Modifier</button>
          {{ form_end(form) }}
        </div>
         <script>
              document.getElementById('upload-icon').addEventListener('click', function() {
              document.getElementById('{{ form.picture.vars.id }}').click();
              });
      </script>
      </header>
    </div>
  </div>
  {% include "partials/_friendslist.html.twig" %}
</div>
{% endblock %}

templates/user/currentUser.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ user.fullname }}{% endblock %}

{% block body %}
{% include "partials/_navBar.html.twig" %}
<div class="row">
{% include "partials/_notification.html.twig" %}
<div class="content-boby">
    <div class="post">
        <div class="post-content">
            <div class="img-post">
                <a href="{{path('current_user')}}">
                    <img src="{{asset(app.user.picture) }}" class="avatar-post">
                </a> 
            </div>  
             
            {{ form_start(postForm) }}
            {{ form_row(postForm.picture, { 'attr': {'style': 'display: none;'} }) }}
            {{ form_row(postForm.content, { 'attr': {'placeholder' : 'Quoi de neuf ?  ( privé ) ' } }) }}
                {{form_rest(postForm)}}
                    <div class="envoyer-post">
                        <i id="upload-icon" class="fa-regular fa-image fa-2xl" ></i>
                        <button class="btn btn-primary">Envoyer</button>
                    </div>
                
            {{ form_end(postForm) }}
        </div>
    </div>
    <script>
        document.getElementById('upload-icon').addEventListener('click', function() {
        document.getElementById('{{ postForm.picture.vars.id }}').click();
        });
    </script>
{# --------   post show ------------ #}
<div class="scroll">
    <ul>
        {% for post in posts %}
        <div class="post-show">
            <div class="img-avatar">
                <a href="{{path('user', {id: post.author.id}) }}">
                    <img src="{{ asset(post.author.picture)}}" alt="" class="avatar" >
                </div>
                <div class="post-show-content">
                    <div class="post-info-user">
                        <h3>@ {{post.author.fullname}}</h3>
                    </a>
                        <small class="justify-content-end mr-10 ">{{post.createdAt | ago(locale= 'fr')}}</small>
                    </div>
                <div class="post-user-content">
                    <p>{{ post.content }}</p>
                    {% if post.picture %}
                        <div class="postimage">
                            <img src="{{ asset(post.picture) }}" class="avatar-post">
                        </div>
                    {% endif %}
                </div>
                <div class="post-user-icone">
                    <div class="row-icone">
                        <div class="comment-icone">
                            <a href="{{path('post_show', {id:post.id})}}">
                                <i class="fa-regular fa-comment fa-lg"></i>
                            </a>
                        </div>
                        <p>{{post.nbresonse}}</p>
                        
                        {% include "partials/_rating.html.twig" with{rating: post.rating, from: 'post', id: post.id} %}
                    </div>
                        
                </div>
            </div>
        </div>
        {% endfor %}
    </ul>
</div>
</div>
{% include "partials/_friendslist.html.twig" %}
</div>
{% endblock %}

templates/user/user.html.twig
{% extends 'base.html.twig' %}

{% block title %}Social World{% endblock %}

{% block body %}
{% include "partials/_navBar.html.twig" %}
<div class="row">
{% include "partials/_notification.html.twig" %}


<div class="content-boby">

    <div class="post-user-info">
        <div class="img-post-user">
            <img src="{{ asset(user.picture)}}"class="">
        </div>
          <div class="row-info-user">
                <h3>@ {{user.fullname}}</h3>
        {% if userFriendshipStatus == 'accepted' %}
            <p>Ami(e)</p>
            <a href="{{path('remove-friend', {'id': user.id}) }}" class="refused-gray"><i class="fa-regular fa-circle-xmark fa-xl"></i></a>
            <a href="{{path('block-user', {'id': user.id}) }}" class="blocked-red"><i class="fa-solid fa-lock fa-xl"></i></a>
        {% elseif userFriendshipStatus == 'pending' %}
            <p>Demande en attente</p>
        {% else %}
            <a href="{{ path('add-friend', {'id': user.id} )}}">
                <i class="fa-solid fa-user-plus fa-2xl"></i>
            </a>
        {% endif %}
        </div>    
    </div>
    
    {% if userFriendshipStatus == 'accepted' %}
    
    <div class="post">
        
        <div class="post-content">
            <div class="img-post">
                <a href="{{path('current_user')}}">
                    <img src="{{asset(app.user.picture) }}" class="avatar-post">
                </a> 
            </div>  
             
        {{ form_start(postForm) }}
        {{ form_row(postForm.picture, { 'attr': {'style': 'display: none;'} }) }}
        {{ form_row(postForm.content, { 'attr': {'placeholder' : 'Écrivez quelque chose à '~ user.firstname } }) }}
                {{form_rest(postForm)}}
                <div class="envoyer-post">
                        <i id="upload-icon" class="fa-regular fa-image fa-2xl" style="cursor: pointer;"></i>
                        <button class="btn btn-primary">Envoyer</button>  
                </div>
        {{ form_end(postForm) }}
        </div>
    </div>
    <script>
        document.getElementById('upload-icon').addEventListener('click', function() {
            document.getElementById('{{ postForm.picture.vars.id }}').click();
        });
    </script>
{# --------   post show ------------ #}
<div class="scroll-user">
    <ul>
        {% for post in posts %}
        <div class="post-show">
            <div class="img-avatar">
                <a href="{{path('user', {id: post.author.id}) }}">
                    <img src="{{ asset(post.author.picture)}}" alt="" class="avatar" >
                </div>
                <div class="post-show-content">
                    <div class="post-info-user">
                        <h3>@ {{post.author.fullname}}</h3>
                    </a>
                        <small class="justify-content-end mr-10 ">{{post.createdAt | ago(locale= 'fr')}}</small>
                    </div>
                <div class="post-user-content">
                    <p>{{ post.content }}</p>
                    {% if post.picture %}
                        <div class="postimage">
                            <img src="{{ asset(post.picture) }}" class="avatar-post">
                        </div>
                    {% endif %}
                </div>
                <div class="post-user-icone">
                    <div class="row-icone">
                        <div class="comment-icone">
                            <a href="{{path('post_show', {id:post.id})}}">
                                <i class="fa-regular fa-comment fa-lg"></i>
                            </a>
                        </div>
                        <p>{{post.nbresonse}}</p>
                        
                        {% include "partials/_rating.html.twig" with{rating: post.rating, from: 'post', id: post.id} %}
                    </div>
                        
                </div>
            </div>
        </div>
        {% endfor %}
    </ul>
</div>
{% endif %}

</div>
{% include "partials/_friendslist.html.twig" %}
</div>
{% endblock %}